// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo9LCDkXHe27a4UnzN9OiM0K-huz9gYQM',
    appId: '1:450229351324:web:4d635aeb86d0c8d6e70e59',
    messagingSenderId: '450229351324',
    projectId: 'nutrihealth-77abb',
    authDomain: 'nutrihealth-77abb.firebaseapp.com',
    storageBucket: 'nutrihealth-77abb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1BKHGiB5SeePsoycccnoyFfAQ8jxaoJ0',
    appId: '1:450229351324:android:f6d2dfdc3f965eb3e70e59',
    messagingSenderId: '450229351324',
    projectId: 'nutrihealth-77abb',
    storageBucket: 'nutrihealth-77abb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDF5M3lRwaZEyxiDWnNHTqBuWwouN8vJLE',
    appId: '1:450229351324:ios:439bb37665af9f75e70e59',
    messagingSenderId: '450229351324',
    projectId: 'nutrihealth-77abb',
    storageBucket: 'nutrihealth-77abb.firebasestorage.app',
    iosBundleId: 'com.example.nutriHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDF5M3lRwaZEyxiDWnNHTqBuWwouN8vJLE',
    appId: '1:450229351324:ios:439bb37665af9f75e70e59',
    messagingSenderId: '450229351324',
    projectId: 'nutrihealth-77abb',
    storageBucket: 'nutrihealth-77abb.firebasestorage.app',
    iosBundleId: 'com.example.nutriHealth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAo9LCDkXHe27a4UnzN9OiM0K-huz9gYQM',
    appId: '1:450229351324:web:f101269222997ae0e70e59',
    messagingSenderId: '450229351324',
    projectId: 'nutrihealth-77abb',
    authDomain: 'nutrihealth-77abb.firebaseapp.com',
    storageBucket: 'nutrihealth-77abb.firebasestorage.app',
  );
}
